export const PAGINATE_ITEMS_REQUEST = 'PAGINATE_ITEMS_REQUEST'
export const PAGINATE_ITEMS_SUCCESS = 'PAGINATE_ITEMS_SUCCESS'
export const PAGINATE_ITEMS_FAILURE = 'PAGINATE_ITEMS_FAILURE'

export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST'
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS'
export const ADD_ITEMS_FAILURE = 'ADD_ITEMS_FAILURE'

export const UPDATE_ITEMS_REQUEST = 'UPDATE_ITEMS_REQUEST'
export const UPDATE_ITEMS_SUCCESS = 'UPDATE_ITEMS_SUCCESS'
export const UPDATE_ITEMS_FAILURE = 'UPDATE_ITEMS_FAILURE'

export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST'
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS'
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE'

export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST'
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS'
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE'

export const LIMIT = 3